# Generated by Django 3.0.3 on 2020-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagreader',
            options={'ordering': ('-scanned',), 'verbose_name': 'Мітка відсканована', 'verbose_name_plural': 'Відскановані мітки'},
        ),
        migrations.AddField(
            model_name='student',
            name='number_scan',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='кількість сканувань'),
        ),
    ]
